# Generated by Django 3.1.3 on 2020-12-27 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shape', models.CharField(choices=[('大型', '大型猫'), ('中型', '中型猫'), ('小型', '小型猫')], max_length=20)),
                ('hair', models.CharField(choices=[('无毛', '无毛猫'), ('短毛', '短毛猫'), ('长毛', '长毛猫')], max_length=20)),
                ('image', models.URLField(max_length=500)),
                ('life', models.CharField(blank=True, max_length=20)),
                ('home', models.CharField(blank=True, max_length=100)),
                ('breed', models.CharField(blank=True, max_length=500)),
                ('character', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shape', models.CharField(choices=[('big', '大型犬'), ('medium', '中型犬'), ('small', '小型犬')], max_length=20)),
                ('hair', models.CharField(choices=[('null', '无毛犬'), ('short', '短毛犬'), ('long', '长毛犬')], max_length=20)),
                ('image', models.URLField(max_length=500)),
                ('life', models.CharField(blank=True, max_length=20)),
                ('home', models.CharField(blank=True, max_length=100)),
                ('breed', models.CharField(blank=True, max_length=1000)),
                ('character', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(default='media/default.png', upload_to='media')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('aboutme', models.TextField(blank=True, default='该用户还没输入个人简介', null=True)),
                ('like', models.CharField(blank=True, choices=[('cat', '猫'), ('dog', '狗')], max_length=10, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
