# Generated by Django 3.1.3 on 2020-12-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('未知', '未知')], default='未知', max_length=10),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='tx'),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='like',
            field=models.CharField(blank=True, choices=[('猫', '猫'), ('狗', '狗'), ('全部', '全部')], max_length=10, null=True),
        ),
    ]
