# Generated by Django 3.1.3 on 2020-12-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patapp', '0002_auto_20201228_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='like',
            field=models.CharField(blank=True, choices=[('猫', '猫'), ('狗', '狗'), ('猫和狗', '猫和狗')], max_length=10, null=True),
        ),
    ]
